# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-exploration',
                'doc_host': 'https://yasaswi-p.github.io',
                'git_url': 'https://github.com/yasaswi-p/nbdev-exploration',
                'lib_path': 'nbdev_exploration'},
  'syms': { 'nbdev_exploration.core': { 'nbdev_exploration.core.add': ('core.html#add', 'nbdev_exploration/core.py'),
                                        'nbdev_exploration.core.divide_numbers': ('core.html#divide_numbers', 'nbdev_exploration/core.py'),
                                        'nbdev_exploration.core.foo': ('core.html#foo', 'nbdev_exploration/core.py'),
                                        'nbdev_exploration.core.subtract_numbers': ( 'core.html#subtract_numbers',
                                                                                     'nbdev_exploration/core.py')},
            'nbdev_exploration.datatools': { 'nbdev_exploration.datatools.add': ('core.html#add', 'nbdev_exploration/datatools.py'),
                                             'nbdev_exploration.datatools.foo': ('core.html#foo', 'nbdev_exploration/datatools.py')},
            'nbdev_exploration.datatools_test': { 'nbdev_exploration.datatools_test.add': ( 'core.html#add',
                                                                                            'nbdev_exploration/datatools_test.py'),
                                                  'nbdev_exploration.datatools_test.foo': ( 'core.html#foo',
                                                                                            'nbdev_exploration/datatools_test.py')}}}
