# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-exploration',
                'doc_host': 'https://yasaswi-p.github.io',
                'git_url': 'https://github.com/yasaswi-p/nbdev-exploration',
                'lib_path': 'nbdev_exploration'},
  'syms': {'nbdev_exploration.core': {'nbdev_exploration.core.foo': ('core.html#foo', 'nbdev_exploration/core.py')}}}
