# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['foo', 'add', 'subtract_numbers', 'divide_numbers']

# %% ../nbs/00_core.ipynb 3
def foo(): pass

# %% ../nbs/00_core.ipynb 4
def add(x, y):
    result = x + y
    return result

# %% ../nbs/00_core.ipynb 6
def subtract_numbers(x, y):
    result = x - y
    return result

# %% ../nbs/00_core.ipynb 9
def divide_numbers(x, y):
    if y == 0:
        return "Error: Cannot divide by zero."
    else:
        result = x / y
        print(f"The division of {x} by {y} results in: {result}")
